### ISSUE TITLE
Set value in percent

### ISSUE THREAD

**Issue by jordanbenzacken** [bytefunc/react-resize-layout#1]
Would it be possible to set value not in px but in percent ?
This would allow to be responsive.

Regards

**Comment by VladBlow** [comment]
@jordanbenzacken Now it's impossible, but I think we can try this.

@bytefunc What do you think about it? It's easy to implement, I can do this.

**Comment by bytefunc** [comment]
@VladBlow  ok
If you implement it. I accept your pull requests.

**Comment by VladBlow** [comment]
https://github.com/bytefunc/react-resize-layout/pull/4

**Comment by VladBlow** [comment]
@bytefunc what do you think about small refactoring?

**Comment by bytefunc** [comment]
@VladBlow 
thanks for pull requests.

**Comment by VladBlow** [comment]
@bytefunc that was cool. Maybe you'd like to improve the library? I have several small ideas and several plans for refactoirng. I can do PR with this.

**Comment by VladBlow** [comment]
I started using your library in my project but didn't find a few things and just copied the code adding the missing parts. Now I have 2 options: make a fork and implement this parts or I can do this in your own project. If you have time to code review and publish new versions, I would be happy.

**Comment by bytefunc** [comment]
Thanks for thinking of my library improve.
but I don't have code review time and not good at english.
if you lot of plan for improve the library. maybe is better to make the fork.

**Comment by bytefunc** [comment]
I found a bug when using percent. please wait for npm update for few days

**Comment by bytefunc** [comment]
@VladBlow
Sorry for replying so late. 
bug is happens when changing the window size.

![bug](https://user-images.githubusercontent.com/21018644/47258740-93a7b200-d4da-11e8-8d5d-ee9a4d675e29.gif)

I checked it with firefox and chrome brower

**Comment by bytefunc** [comment]
I fixed this bug and i tried lot of refactoirng

**Comment by bytefunc** [comment]
@VladBlow Thanks for pull requests.
I did push the new version to npm and I'm going to close this issue.
